-- 코드를 입력하세요

select REST_INFO.REST_ID, REST_INFO.REST_NAME, REST_INFO.FOOD_TYPE, REST_INFO.FAVORITES, REST_INFO.ADDRESS, round(avg(REST_REVIEW.REVIEW_SCORE), 2) as SCORE from REST_INFO join REST_REVIEW on REST_INFO.REST_ID=REST_REVIEW.REST_ID where ADDRESS like '서울%' group by REST_INFO.REST_ID  order by SCORE desc, sum(REST_INFO.FAVORITES) desc;